import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://scjzofjyxmchfjsngqtb.supabase.co','sb_publishable_EGlr-6w0xh4gD8OImboE_Q_V-COJ7t9');

const DAY_START=8*60;
const DAY_END=22*60;
const LAST_VISIBLE_START=21*60+45;
const PX_PER_MINUTE=2;
const SNAP_MINUTES=15;
const DOWN_TRIGGER=10;
const HORIZONTAL_CANCEL=34;
const EDGE_ZONE=72;
const MAX_AUTO_SPEED=13;

let active=null,autoFrame=null,suppressClickUntil=0,realtimeChannel=null,realtimeTimer=null,hiddenAt=0,lastAutoDate=null,enhanceTimer=null,suppressRealtimeUntil=0,suppressQuarterEnhanceUntil=0;
let blockedRows=[],blockedRowsDate='';
const bookingCache=new Map();
const $=id=>document.getElementById(id);
const getScheduleScroll=()=>document.querySelector('.timelineScroll,.scheduleScroll');
const selectedDate=()=>$('date')?.value||'';
const isAdmin=()=>location.pathname.endsWith('/admin.html')||location.pathname.endsWith('/');
const isBookings=()=>location.pathname.endsWith('/bookings.html');

function timeToMinutes(t){const[h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m}
function minutesToTime(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}:00`}
function snapMinutes(v){return Math.round(v/SNAP_MINUTES)*SNAP_MINUTES}
function overlaps(aStart,aEnd,bStart,bEnd){return aStart<bEnd&&aEnd>bStart}
function todayJapan(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value;return `${g('year')}-${g('month')}-${g('day')}`}
function currentJapanMinutes(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),g=t=>Number(p.find(x=>x.type===t)?.value||0);return g('hour')*60+g('minute')}
function monthDates(month){if(!/^\d{4}-\d{2}$/.test(month||''))return[];const[y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate(),out=[];for(let d=1;d<=last;d++)out.push(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`);return out}
function nextMonth(month){const[y,m]=month.split('-').map(Number),d=new Date(Date.UTC(y,m,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-01`}
function quarterTimes(){const out=[];for(let n=DAY_START;n<=LAST_VISIBLE_START;n+=15)out.push(minutesToTime(n));return out}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function displayEndTime(t){return String(t||'').startsWith('23:59')?'23:59':String(t||'').slice(0,5)}
function blockEndMinutes(t){return String(t||'').startsWith('23:59')?24*60:timeToMinutes(t)}

function addStyles(){
  if($('nakanoUnifiedBookingStyle'))return;
  const s=document.createElement('style');s.id='nakanoUnifiedBookingStyle';s.textContent=`
.bookingBlock{user-select:none;-webkit-user-select:none;-webkit-touch-callout:none;touch-action:pan-x;position:absolute}.bookingBlock.dragging,.bookingBlock.resizing{z-index:100!important;opacity:.97;box-shadow:0 0 0 3px rgba(97,87,77,.20),0 9px 26px rgba(0,0,0,.23);transition:none!important;touch-action:none!important}.bookingBlock.dragging{transform:translateY(10px) scale(1.025)}.bookingBlock.resizing{transform:translateY(4px)}body.bookingDragging{overscroll-behavior:none}body.bookingDragging .timelineScroll,body.bookingDragging .scheduleScroll{touch-action:none!important;overscroll-behavior:none}
.bookingResizeHandle{position:absolute;right:0;top:0;bottom:0;width:20px;z-index:8;cursor:ew-resize;touch-action:none;background:linear-gradient(to left,rgba(97,87,77,.13),rgba(97,87,77,.02));border-left:1px dashed rgba(97,87,77,.38)}.bookingResizeHandle:after{content:'↔';position:absolute;right:2px;top:50%;transform:translateY(-50%);font-size:11px;color:#746b63;font-weight:800}.bookingBlock.resizing .bookingResizeHandle{background:rgba(97,87,77,.20)}
.bookingOriginGhost{position:absolute;top:8px;height:82px;z-index:4;pointer-events:none;border:2px dashed rgba(92,88,84,.42);border-radius:10px;background:rgba(92,88,84,.13);box-shadow:inset 0 0 0 1px rgba(255,255,255,.35);display:flex;align-items:center;justify-content:center;color:rgba(70,67,64,.68);font-size:10px;font-weight:700}.bookingOriginGhost span{padding:3px 6px;border-radius:7px;background:rgba(255,255,255,.70);white-space:nowrap}
.dragDestinationSlot{height:34px;display:flex;align-items:center;justify-content:center;margin:2px 0 6px;pointer-events:none}.dragDestinationPill{opacity:0;transform:translateY(2px);min-width:150px;padding:5px 12px 6px;border:1px solid #cfc4b9;border-radius:11px;background:#fff;color:#332f2b;text-align:center;box-shadow:0 2px 9px rgba(0,0,0,.09);transition:opacity .08s ease,transform .08s ease}.dragDestinationSlot.show .dragDestinationPill{opacity:1;transform:translateY(0)}.dragDestinationLabel{font-size:10px;color:#77716a;margin-right:6px}.dragDestinationTime{font-size:17px;font-weight:800}
.dragEdge{position:fixed;top:0;bottom:0;width:54px;opacity:0;z-index:99998;pointer-events:none;transition:opacity .12s}.dragEdge.left{left:0;background:linear-gradient(to right,rgba(97,87,77,.18),transparent)}.dragEdge.right{right:0;background:linear-gradient(to left,rgba(97,87,77,.18),transparent)}.dragEdge.show{opacity:1}
.bookingOperationGuide{margin-top:9px;padding:10px 11px;border:1px solid #e7e0d7;border-radius:12px;background:#faf8f5;color:#68615b;font-size:12px;line-height:1.65}.bookingOperationShort{font-weight:700;color:#514b45}.bookingOperationGuide details{margin-top:5px}.bookingOperationGuide summary{cursor:pointer;list-style:none;color:#777069;font-size:12px}.bookingOperationGuide summary::-webkit-details-marker{display:none}.bookingOperationDetail{padding-top:8px;color:#746d67;line-height:1.75}.bookingRefreshRow{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px}.bookingRefreshStatus{color:#8a837d;font-size:11px}.bookingRefreshButton{width:auto!important;min-width:72px;padding:7px 10px;border:1px solid #ddd5cc;border-radius:10px;background:#fff;color:#554e48;font-size:12px;font-weight:700}
.blockedSchedule,.blockedBlock{cursor:pointer!important;user-select:none;-webkit-user-select:none}.blockedSchedule.blockedSelected,.blockedBlock.blockedSelected{box-shadow:0 0 0 3px rgba(138,74,66,.22),0 3px 10px rgba(0,0,0,.10);z-index:12!important}.blockedTapHint{display:block;margin-top:3px;font-size:9px;opacity:.72;white-space:nowrap}
.blockedInlineEditor{display:none;margin:8px 0 10px;padding:12px;border:1px solid #d8aaa5;border-radius:14px;background:#fff8f7}.blockedInlineEditor.open{display:block}.blockedEditorTitle{font-size:14px;font-weight:800;color:#6f4842;margin-bottom:8px}.blockedEditorRow{display:grid;grid-template-columns:1fr 1fr;gap:8px}.blockedInlineEditor label{display:block;margin:0;font-size:11px;font-weight:700;color:#6d655f}.blockedInlineEditor select,.blockedInlineEditor input{width:100%;height:42px;margin:5px 0 0;padding:9px 10px;border:1px solid #ddd5cc;border-radius:10px;background:#fff;color:#342f2b}.blockedEditorActions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.blockedEditorActions button{width:100%!important;margin:0!important;padding:10px 5px!important;border-radius:10px!important;font-size:12px;font-weight:700}.blockedSave{background:#61574d;color:#fff;border:1px solid #61574d}.blockedClose{background:#fff;color:#4d4843;border:1px solid #d8d0c7}.blockedDelete{background:#fff;color:#9b4138;border:1px solid #d8aaa5}.blockedBook{background:#fff7ef;color:#7a4d2f;border:1px solid #d9b99f}.blockedEditorMsg{min-height:18px;margin-top:7px;color:#8a433b;font-size:11px;line-height:1.5}
.blockedFold,.monthlyBookingFold{margin-top:12px;border:1px solid #e7e0d7;border-radius:13px;overflow:hidden}.blockedFold>summary,.monthlyBookingFold>summary{padding:13px;background:#faf8f5;font-weight:700;cursor:pointer;list-style:none}.blockedFold>summary::-webkit-details-marker,.monthlyBookingFold>summary::-webkit-details-marker{display:none}.blockedFoldInner,.monthlyBookingInner{padding:0 12px 10px}.monthlyBookingRow{padding:10px 8px;border-bottom:1px solid #eee7df;font-size:12px;line-height:1.55;cursor:pointer;border-radius:9px;user-select:none;-webkit-user-select:none}.monthlyBookingRow:last-child{border-bottom:0}.monthlyBookingRow:active{background:#f3eee9}.monthlyBookingTime{font-weight:800;font-size:13px}.monthlyBookingEditHint{margin-top:3px;color:#8a8179;font-size:10px}.monthlyBookingCount{color:#77716a;font-weight:600;margin-left:5px}
.quarterGuide{position:absolute;top:0;height:100%;border-left:1px dashed rgba(122,114,106,.32);pointer-events:none;z-index:2}.quarterOpenOverlay{position:absolute;top:0;height:100%;z-index:1;pointer-events:none;border-left:1px solid rgba(122,114,106,.12)}.quarterOpenOverlay.open{background:#f1f7f2}.quarterOpenOverlay.closed{background:#f1f0ee}
#slots.hourlySlots{display:block!important}.hourSlotGroup{border:1px solid #e7e0d7;border-radius:13px;background:#faf8f5;margin:8px 0;padding:9px}.hourSlotTitle{font-size:14px;font-weight:800;margin-bottom:7px}.hourSlotButtons{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.hourQuarter{min-width:0;padding:9px 2px;border:1px solid #ddd5cc;border-radius:10px;background:#fff;font-size:12px;font-weight:700}.hourQuarter.open{background:#eaf3ec;color:#168047}.hourQuarter.closed{background:#eeeeec;color:#8a8580}.hourQuarter.busy{background:#f6dddd;color:#9b4138}
@media(max-width:500px){.blockedEditorRow{grid-template-columns:1fr 1fr}.blockedEditorActions{grid-template-columns:repeat(2,minmax(0,1fr))}}
`;
  document.head.appendChild(s);
}

function renamePages(){if(isBookings()){document.title='整体なかの｜当日予約一覧';const p=[...document.querySelectorAll('p')].find(x=>x.textContent.includes('予約一覧・スケジュール'));if(p)p.textContent='当日予約一覧・スケジュール'}document.querySelectorAll('button').forEach(b=>{if(b.textContent.trim()==='予約一覧')b.textContent='当日予約一覧'})}
function ensureDestinationSlot(){const scroll=getScheduleScroll();if(!scroll)return null;let slot=$('dragDestinationSlot');if(slot)return slot;slot=document.createElement('div');slot.id='dragDestinationSlot';slot.className='dragDestinationSlot';slot.innerHTML='<div class="dragDestinationPill"><span class="dragDestinationLabel">変更先</span><span class="dragDestinationTime">--:--</span></div>';scroll.insertAdjacentElement('beforebegin',slot);return slot}
function showDestination(t){const s=ensureDestinationSlot();if(!s)return;const b=s.querySelector('.dragDestinationTime');if(b)b.textContent=t;s.classList.add('show')}
function hideDestination(){$('dragDestinationSlot')?.classList.remove('show')}
function createGuide(){const scroll=getScheduleScroll();if(!scroll||$('bookingOperationGuide'))return;const g=document.createElement('div');g.id='bookingOperationGuide';g.className='bookingOperationGuide';g.innerHTML=`<div class="bookingOperationShort">予約：本体を下→左右で開始時刻 ／ 右端 ↔ で長さ変更　・　予約不可／予定：タップで変更・削除 ／ 左右ドラッグで時間移動</div><details><summary>操作方法を詳しく見る ▼</summary><div class="bookingOperationDetail">予約の開始時間と施術時間は15分単位で変更できます。<br>赤い「予約不可／予定」はタップで変更・削除、左右へドラッグすると長さを保ったまま15分単位で移動できます。予定編集から同じ時間に店側の新規予約も追加できます。<br>CLOSE・他の予約などと矛盾する予約変更は保存されません。</div></details><div class="bookingRefreshRow"><span id="bookingRefreshStatus" class="bookingRefreshStatus">自動更新 ON</span><button id="bookingManualRefresh" class="bookingRefreshButton" type="button">↻ 更新</button></div>`;scroll.insertAdjacentElement('afterend',g);$('bookingManualRefresh')?.addEventListener('click',()=>location.reload())}
function createEdges(){if($('dragEdgeLeft'))return;for(const[id,c]of[['dragEdgeLeft','left'],['dragEdgeRight','right']]){const d=document.createElement('div');d.id=id;d.className=`dragEdge ${c}`;document.body.appendChild(d)}}
function hideEdges(){$('dragEdgeLeft')?.classList.remove('show');$('dragEdgeRight')?.classList.remove('show')}

async function fetchBookingById(id,force=false){if(!id)throw new Error('予約IDがありません');if(!force&&bookingCache.has(id))return bookingCache.get(id);const{data,error}=await supabase.from('nakano_bookings').select('*').eq('id',id).single();if(error)throw error;bookingCache.set(id,data);return data}
function inferDurationFromBlock(el){const d=Number(el.dataset.duration);if(d>0)return d;const w=parseFloat(el.style.width)||el.getBoundingClientRect().width||60;return Math.max(15,Math.round((w/PX_PER_MINUTE)/15)*15)}
function ensureResizeHandle(el){if(el.querySelector('.bookingResizeHandle'))return;const h=document.createElement('span');h.className='bookingResizeHandle';h.title='左右に動かして施術時間を変更';h.setAttribute('aria-label','施術時間を変更');el.appendChild(h)}
async function hydrateBlock(el){if(el.dataset.hydrating==='1')return;el.dataset.hydrating='1';ensureResizeHandle(el);const id=el.dataset.bookingId;if(!id){el.dataset.hydrating='0';return}try{const b=await fetchBookingById(id);const d=Number(b.minutes)||30;el.dataset.duration=String(d);el.dataset.startTime=String(b.start_time).slice(0,5);el.style.width=`${Math.max(44,d*PX_PER_MINUTE)}px`}catch(e){console.warn('予約カードの時間取得に失敗',e)}finally{el.dataset.hydrating='0'}}
function scanBlocks(){document.querySelectorAll('.bookingBlock').forEach(attachBlock)}
function attachBlock(el){ensureResizeHandle(el);hydrateBlock(el);if(el.dataset.dragUnified)return;el.dataset.dragUnified='1';el.addEventListener('pointerdown',e=>pointerDown(e,el));el.addEventListener('contextmenu',e=>e.preventDefault());el.addEventListener('dragstart',e=>e.preventDefault())}

function immediateStateFromBlock(e,el,scroll,mode){const text=el.dataset.startTime||el.querySelector('.bookingTime')?.textContent?.trim().slice(0,5)||'',om=timeToMinutes(text);if(!Number.isFinite(om))return null;const duration=inferDurationFromBlock(el);return{mode,element:el,bookingId:el.dataset.bookingId||'',duration,originalDuration:duration,newDuration:duration,scrollElement:scroll,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,currentX:e.clientX,currentY:e.clientY,startScrollLeft:scroll.scrollLeft,originalMinutes:om,newMinutes:om,originalLeft:(om-DAY_START)*PX_PER_MINUTE,originalTime:text,interacting:false,originGhost:null}}
function createOriginGhost(s){removeOriginGhost(s);const lane=s.element.parentElement;if(!lane)return;const g=document.createElement('div');g.className='bookingOriginGhost';g.style.left=`${s.originalLeft}px`;g.style.width=`${Math.max(44,s.originalDuration*PX_PER_MINUTE)}px`;g.innerHTML=`<span>元 ${s.originalTime}・${s.originalDuration}分</span>`;lane.insertBefore(g,s.element);s.originGhost=g}
function removeOriginGhost(s){if(s?.originGhost){s.originGhost.remove();s.originGhost=null}}
function startInteraction(s,e){s.interacting=true;createOriginGhost(s);s.element.classList.add(s.mode==='resize'?'resizing':'dragging');document.body.classList.add('bookingDragging');try{s.element.setPointerCapture(e.pointerId)}catch{}try{navigator.vibrate?.(12)}catch{}if(s.mode==='resize')showDestination(`${s.originalTime}–${minutesToTime(s.originalMinutes+s.originalDuration).slice(0,5)}（${s.originalDuration}分）`);else showDestination(s.originalTime);stopAutoScroll();autoFrame=requestAnimationFrame(autoScrollLoop)}
function pointerDown(e,el){if(active||(e.pointerType==='mouse'&&e.button!==0))return;const scroll=el.closest('.timelineScroll,.scheduleScroll');if(!scroll)return;const mode=e.target.closest('.bookingResizeHandle')?'resize':'move';active=immediateStateFromBlock(e,el,scroll,mode);if(!active)return;if(mode==='resize'){e.preventDefault();e.stopPropagation();startInteraction(active,e)}}
function updateMove(){const s=active;if(!s?.interacting)return;const scroll=s.scrollElement,moved=(s.currentX-s.startX+scroll.scrollLeft-s.startScrollLeft)/PX_PER_MINUTE;let next=snapMinutes(s.originalMinutes+moved);next=Math.max(DAY_START,Math.min(DAY_END-s.duration,next));s.newMinutes=next;s.element.style.left=`${(next-DAY_START)*PX_PER_MINUTE}px`;const label=minutesToTime(next).slice(0,5),box=s.element.querySelector('.bookingTime');if(box)box.textContent=label;showDestination(label)}
function updateResize(){const s=active;if(!s?.interacting)return;const scroll=s.scrollElement,moved=(s.currentX-s.startX+scroll.scrollLeft-s.startScrollLeft)/PX_PER_MINUTE,maxDuration=Math.min(360,DAY_END-s.originalMinutes);let next=snapMinutes(s.originalDuration+moved);next=Math.max(15,Math.min(maxDuration,next));s.newDuration=next;s.element.style.width=`${Math.max(44,next*PX_PER_MINUTE)}px`;const end=minutesToTime(s.originalMinutes+next).slice(0,5),box=s.element.querySelector('.bookingTime');if(box)box.textContent=`${s.originalTime}–${end}`;showDestination(`${s.originalTime}–${end}（${next}分）`)}
function updateActive(){if(active?.mode==='resize')updateResize();else updateMove()}
function pointerMove(e){if(!active||active.pointerId!==e.pointerId)return;active.currentX=e.clientX;active.currentY=e.clientY;if(active.mode==='resize'){e.preventDefault();updateResize();return}const dx=active.currentX-active.startX,dy=active.currentY-active.startY;if(!active.interacting){if(dy>=DOWN_TRIGGER&&Math.abs(dx)<=48){e.preventDefault();startInteraction(active,e);return}if(Math.abs(dx)>=HORIZONTAL_CANCEL&&Math.abs(dx)>Math.abs(dy)*1.15){active=null;return}return}e.preventDefault();updateMove()}
function stopAutoScroll(){if(autoFrame){cancelAnimationFrame(autoFrame);autoFrame=null}hideEdges()}
function autoScrollLoop(){if(!active?.interacting){stopAutoScroll();return}const scroll=active.scrollElement,rect=scroll.getBoundingClientRect(),x=active.currentX,ld=x-rect.left,rd=rect.right-x;let speed=0;hideEdges();if(ld<EDGE_ZONE){const p=Math.max(0,Math.min(1,(EDGE_ZONE-ld)/EDGE_ZONE));speed=-(3+p*MAX_AUTO_SPEED);$('dragEdgeLeft')?.classList.add('show')}else if(rd<EDGE_ZONE){const p=Math.max(0,Math.min(1,(EDGE_ZONE-rd)/EDGE_ZONE));speed=3+p*MAX_AUTO_SPEED;$('dragEdgeRight')?.classList.add('show')}if(speed){const before=scroll.scrollLeft;scroll.scrollLeft+=speed;if(before!==scroll.scrollLeft)updateActive()}autoFrame=requestAnimationFrame(autoScrollLoop)}
function cleanupInteraction(s){s.element.classList.remove('dragging','resizing');document.body.classList.remove('bookingDragging');removeOriginGhost(s);hideDestination();stopAutoScroll()}
function restoreCard(s){s.element.style.left=`${s.originalLeft}px`;s.element.style.width=`${Math.max(44,s.originalDuration*PX_PER_MINUTE)}px`;const t=s.element.querySelector('.bookingTime');if(t)t.textContent=s.originalTime}
async function saveNewTime(b,n){const nt=minutesToTime(n),ol=String(b.start_time).slice(0,5),nl=nt.slice(0,5);if(ol===nl)return'same';if(!confirm(`${ol} → ${nl} に予約開始時間を変更しますか？`))return false;const{error}=await supabase.rpc('nakano_admin_move_booking',{p_booking_id:b.id,p_start_time:nt});if(error){console.error(error);alert('その時間には移動できません。OPEN/CLOSE・予約不可時間・他の予約を確認してください。');return false}return true}
async function saveNewDuration(b,n){const old=Number(b.minutes)||30;if(old===n)return'same';const start=String(b.start_time).slice(0,5),end=minutesToTime(timeToMinutes(start)+n).slice(0,5);if(!confirm(`施術時間を ${old}分 → ${n}分（${start}〜${end}）に変更しますか？`))return false;const{error}=await supabase.rpc('nakano_admin_resize_booking',{p_booking_id:b.id,p_minutes:n});if(error){console.error(error);alert('その長さには変更できません。延長先のOPEN/CLOSE・予約不可時間・他の予約を確認してください。');return false}return true}
async function pointerUp(e){if(!active||active.pointerId!==e.pointerId)return;const s=active;active=null;if(!s.interacting)return;suppressClickUntil=Date.now()+900;cleanupInteraction(s);const changed=s.mode==='resize'?s.newDuration!==s.originalDuration:s.newMinutes!==s.originalMinutes;if(!changed){restoreCard(s);return}try{const b=await fetchBookingById(s.bookingId,true),r=s.mode==='resize'?await saveNewDuration(b,s.newDuration):await saveNewTime(b,s.newMinutes);if(r===true){setTimeout(()=>location.reload(),160);return}}catch(err){console.error(err);alert('予約情報を確認できませんでした。画面を更新してもう一度お試しください。')}restoreCard(s)}
function pointerCancel(){if(!active)return;const s=active;active=null;if(s.interacting)restoreCard(s);cleanupInteraction(s)}
document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil&&e.target.closest('.bookingBlock')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}},true);

function ensureBlockedEditor(){
  const scroll=getScheduleScroll();if(!scroll)return null;
  let editor=$('blockedInlineEditor');if(editor)return editor;
  editor=document.createElement('div');editor.id='blockedInlineEditor';editor.className='blockedInlineEditor';
  const startOpts=quarterTimes().map(t=>`<option value="${t.slice(0,5)}">${t.slice(0,5)}</option>`).join('');
  const endOpts=[...quarterTimes().slice(1).map(t=>t.slice(0,5)),'23:00','23:59'].filter((v,i,a)=>a.indexOf(v)===i).map(t=>`<option value="${t}">${t}</option>`).join('');
  editor.innerHTML=`<div class="blockedEditorTitle">予約不可／予定の時間を変更</div><div class="blockedEditorRow"><label>開始<select id="blockedInlineStart">${startOpts}</select></label><label>終了<select id="blockedInlineEnd">${endOpts}</select></label></div><label style="margin-top:8px">予定名・メモ<input id="blockedInlineMemo" placeholder="例：外出・休憩・予約不可"></label><div class="blockedEditorActions"><button type="button" class="blockedSave" id="blockedInlineSave">変更を保存</button><button type="button" class="blockedBook" id="blockedInlineBook">この時間から新規予約</button><button type="button" class="blockedDelete" id="blockedInlineDelete">予定を削除</button><button type="button" class="blockedClose" id="blockedInlineClose">閉じる</button></div><div id="blockedInlineMsg" class="blockedEditorMsg"></div>`;
  scroll.insertAdjacentElement('afterend',editor);
  $('blockedInlineClose').onclick=closeBlockedEditor;
  $('blockedInlineSave').onclick=saveBlockedEditor;
  $('blockedInlineBook').onclick=bookBlockedAsBooking;
  $('blockedInlineDelete').onclick=deleteBlockedEditor;
  return editor;
}
function clearBlockedSelection(){document.querySelectorAll('.blockedSchedule.blockedSelected,.blockedBlock.blockedSelected').forEach(x=>x.classList.remove('blockedSelected'))}
function closeBlockedEditor(){const ed=$('blockedInlineEditor');if(ed){ed.classList.remove('open');delete ed.dataset.blockedId}clearBlockedSelection()}
function openBlockedEditor(item,sourceEl=null){
  if(!item?.id)return;const editor=ensureBlockedEditor();if(!editor)return;
  editor.dataset.blockedId=item.id;editor.dataset.blockedDate=item.blocked_date||selectedDate();
  $('blockedInlineStart').value=String(item.start_time).slice(0,5);
  const end=displayEndTime(item.end_time);if(![...$('blockedInlineEnd').options].some(o=>o.value===end)){const o=document.createElement('option');o.value=end;o.textContent=end;$('blockedInlineEnd').appendChild(o)}$('blockedInlineEnd').value=end;
  $('blockedInlineMemo').value=item.memo||'';$('blockedInlineMsg').textContent='';
  clearBlockedSelection();if(sourceEl)sourceEl.classList.add('blockedSelected');
  editor.classList.add('open');editor.scrollIntoView({behavior:'smooth',block:'nearest'});
}
async function validateBlockedRange(item,start,end){
  const date=item.blocked_date||selectedDate(),s=timeToMinutes(start),e=end==='23:59'?24*60:timeToMinutes(end);if(!Number.isFinite(s)||!Number.isFinite(e)||e<=s)return'終了時間は開始時間より後にしてください。';
  const{data,error}=await supabase.from('nakano_bookings').select('id,start_time,minutes,customer_name').eq('booking_date',date).eq('status','confirmed');if(error)return'予約状況を確認できませんでした。';
  const hit=(data||[]).find(b=>overlaps(s,e,timeToMinutes(b.start_time),timeToMinutes(b.start_time)+(Number(b.minutes)||30)));if(hit)return`${String(hit.start_time).slice(0,5)}の予約と重なります。先に予約時間を調整してください。`;
  return'';
}
async function saveBlockedEditor(){
  const ed=$('blockedInlineEditor'),id=ed?.dataset.blockedId;if(!id)return;const item=blockedRows.find(x=>String(x.id)===String(id));if(!item)return;
  const start=$('blockedInlineStart').value,end=$('blockedInlineEnd').value,memo=$('blockedInlineMemo').value.trim(),msg=$('blockedInlineMsg');msg.textContent='確認しています…';
  const invalid=await validateBlockedRange(item,start,end);if(invalid){msg.textContent=invalid;return}
  $('blockedInlineSave').disabled=true;msg.textContent='保存しています…';
  const{error}=await supabase.from('nakano_blocked_times').update({start_time:`${start}:00`,end_time:end==='23:59'?'23:59:00':`${end}:00`,memo:memo||null}).eq('id',id);
  if(error){console.error(error);msg.textContent='変更できませんでした。';$('blockedInlineSave').disabled=false;return}
  msg.textContent='変更しました。';setTimeout(()=>location.reload(),180);
}
function bookBlockedAsBooking(){
  const ed=$('blockedInlineEditor'),id=ed?.dataset.blockedId;
  if(!id)return;
  const item=blockedRows.find(x=>String(x.id)===String(id));
  if(!item)return;
  const date=ed.dataset.blockedDate||item.blocked_date||selectedDate();
  const start=String($('blockedInlineStart')?.value||item.start_time||'').slice(0,5);
  closeBlockedEditor();
  window.dispatchEvent(new CustomEvent('nakano-admin-prefill-booking',{detail:{date,start_time:start,blocked_id:id}}));
}

async function deleteBlockedEditor(){
  const ed=$('blockedInlineEditor'),id=ed?.dataset.blockedId;if(!id)return;if(!confirm('この予約不可／予定を削除しますか？'))return;
  $('blockedInlineDelete').disabled=true;const{error}=await supabase.from('nakano_blocked_times').delete().eq('id',id);if(error){console.error(error);$('blockedInlineMsg').textContent='削除できませんでした。';$('blockedInlineDelete').disabled=false;return}setTimeout(()=>location.reload(),150);
}
function inferBlockedFromElement(el,rows){
  const left=parseFloat(el.style.left)||0,width=parseFloat(el.style.width)||0,start=Math.round(DAY_START+left/PX_PER_MINUTE),duration=Math.max(15,Math.round((width/PX_PER_MINUTE)/15)*15);
  let best=null,bestScore=Infinity;for(const r of rows){const rs=timeToMinutes(r.start_time),re=blockEndMinutes(r.end_time),score=Math.abs(rs-start)*8+Math.abs((re-rs)-duration);if(score<bestScore){best=r;bestScore=score}}return bestScore<=75?best:null;
}
async function hydrateBlockedBlocks(force=false){
  const date=selectedDate();if(!date)return;const els=[...document.querySelectorAll('.blockedSchedule,.blockedBlock')];if(!els.length)return;
  if(force||blockedRowsDate!==date){const{data,error}=await supabase.from('nakano_blocked_times').select('id,blocked_date,start_time,end_time,memo').eq('blocked_date',date).order('start_time');if(error){console.warn('予約不可時間の取得に失敗',error);return}blockedRows=data||[];blockedRowsDate=date}
  for(const el of els){let item=blockedRows.find(r=>String(r.id)===String(el.dataset.blockedId));if(!item)item=inferBlockedFromElement(el,blockedRows);if(!item)continue;el.dataset.blockedId=item.id;el.title=`${String(item.start_time).slice(0,5)}〜${displayEndTime(item.end_time)} タップで編集／左右ドラッグで移動`;if(!el.querySelector('.blockedTapHint')){const h=document.createElement('span');h.className='blockedTapHint';h.textContent='タップで編集・左右ドラッグで移動';el.appendChild(h)}if(el.dataset.blockedTapReady!=='1'){el.dataset.blockedTapReady='1';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const row=blockedRows.find(r=>String(r.id)===String(el.dataset.blockedId));if(row)openBlockedEditor(row,el)})}}
}

function scrollToCurrentTime(force=false){const scroll=getScheduleScroll(),date=selectedDate();if(!scroll||!date)return;if(date!==todayJapan()){if(force||lastAutoDate!==date){scroll.scrollLeft=0;lastAutoDate=date}return}if(!force&&lastAutoDate===date)return;scroll.scrollLeft=Math.max(0,(currentJapanMinutes()-DAY_START)*PX_PER_MINUTE-scroll.clientWidth/2);lastAutoDate=date}
function setupDateWatch(){const d=$('date');if(!d)return;d.addEventListener('change',()=>{lastAutoDate=null;blockedRowsDate='';closeBlockedEditor();setTimeout(()=>{scrollToCurrentTime(true);addQuarterGuides();refreshQuarterUI();loadMonthlyBookings();hydrateBlockedBlocks(true)},240)})}
function setupRealtime(){try{realtimeChannel=supabase.channel(`nakano-management-${Date.now()}`);const reload=()=>{if(Date.now()<suppressRealtimeUntil)return;clearTimeout(realtimeTimer);realtimeTimer=setTimeout(()=>{if(!active?.interacting&&!$('blockedInlineEditor')?.classList.contains('open'))location.reload()},650)};const refreshSlots=()=>{if(Date.now()<suppressRealtimeUntil)return;clearTimeout(realtimeTimer);realtimeTimer=setTimeout(()=>{if(!active?.interacting&&!$('blockedInlineEditor')?.classList.contains('open'))refreshOpenCloseUI()},220)};for(const table of['nakano_bookings','nakano_blocked_times'])realtimeChannel.on('postgres_changes',{event:'*',schema:'public',table},reload);realtimeChannel.on('postgres_changes',{event:'*',schema:'public',table:'nakano_open_slots'},refreshSlots);realtimeChannel.subscribe(status=>{const b=$('bookingRefreshStatus');if(!b)return;if(status==='SUBSCRIBED')b.textContent='自動更新 ON';else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')b.textContent='自動更新 再接続待ち'})}catch(e){console.error('Realtime設定エラー',e)}}
function refreshAfterResume(){if(!active?.interacting&&!$('blockedInlineEditor')?.classList.contains('open'))location.reload()}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){hiddenAt=Date.now();return}if(document.visibilityState==='visible'&&hiddenAt&&Date.now()-hiddenAt>1000)refreshAfterResume()});window.addEventListener('pageshow',e=>{if(e.persisted)refreshAfterResume()});window.addEventListener('focus',()=>{if(hiddenAt&&Date.now()-hiddenAt>1500)refreshAfterResume()});

function improveAdminLayout(){if(!isAdmin())return;const admin=$('adminArea');if(!admin)return;const cards=[...admin.querySelectorAll(':scope > section.card')],addCard=cards.find(c=>c.querySelector('#addBooking')),blockCard=cards.find(c=>c.querySelector('#blockedList')),openCard=cards.find(c=>c.querySelector('#slots'));if(addCard&&openCard&&addCard.previousElementSibling!==openCard)openCard.insertAdjacentElement('afterend',addCard);if(blockCard)ensureBlockedFold(blockCard);ensureMonthlyBookingFold()}
function ensureBlockedFold(blockCard){if(blockCard.dataset.foldReady==='1')return;const list=$('blockedList'),h=[...blockCard.querySelectorAll('h3')].find(x=>x.textContent.includes('この月の予約不可一覧'));if(!list||!h)return;const hr=h.previousElementSibling;if(hr?.tagName==='HR')hr.remove();const d=document.createElement('details');d.className='blockedFold';d.innerHTML='<summary>この月の予約不可一覧 ▼</summary><div class="blockedFoldInner"></div>';h.replaceWith(d);d.querySelector('.blockedFoldInner').appendChild(list);blockCard.dataset.foldReady='1'}
function ensureMonthlyBookingFold(){if(!isAdmin()||$('monthlyBookingsCard'))return;const schedule=$('scheduleScroll')?.closest('section.card');if(!schedule)return;const card=document.createElement('section');card.className='card';card.id='monthlyBookingsCard';card.innerHTML=`<details class="monthlyBookingFold"><summary>今月の予約一覧 <span id="monthlyBookingCount" class="monthlyBookingCount"></span> ▼</summary><div class="monthlyBookingInner"><div id="monthlyBookingList" class="muted">読み込んでいます…</div></div></details>`;card.addEventListener('click',e=>{const row=e.target.closest?.('.monthlyBookingRow[data-booking-id]');if(!row)return;openMonthlyBooking(row.dataset.bookingId,row.dataset.bookingDate)});schedule.insertAdjacentElement('afterend',card);loadMonthlyBookings()}
async function openMonthlyBooking(id,date){
  const input=$('date');
  if(!id)return;
  if(input&&date&&input.value!==date){
    input.value=date;
    input.dispatchEvent(new Event('change',{bubbles:true}));
  }
  const started=Date.now();
  const findAndOpen=()=>{
    const block=[...document.querySelectorAll('.bookingBlock[data-booking-id]')].find(el=>String(el.dataset.bookingId)===String(id));
    if(block){
      block.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});
      setTimeout(()=>block.click(),120);
      return;
    }
    if(Date.now()-started<3000)setTimeout(findAndOpen,120);
  };
  findAndOpen();
}
async function loadMonthlyBookings(){if(!isAdmin()||!$('monthlyBookingList'))return;const month=$('month')?.value||selectedDate().slice(0,7);if(!month)return;const first=`${month}-01`,next=nextMonth(month),box=$('monthlyBookingList');box.textContent='読み込んでいます…';const{data,error}=await supabase.from('nakano_bookings').select('id,booking_date,start_time,minutes,menu_name,customer_name,status').gte('booking_date',first).lt('booking_date',next).eq('status','confirmed').order('booking_date').order('start_time');if(error){box.textContent='予約一覧を読み込めませんでした。';return}const rows=data||[];$('monthlyBookingCount').textContent=`${rows.length}件`;if(!rows.length){box.innerHTML='<span class="muted">この月の予約はありません。</span>';return}box.innerHTML=rows.map(b=>`<div class="monthlyBookingRow" data-booking-id="${esc(b.id)}" data-booking-date="${esc(b.booking_date)}"><div class="monthlyBookingTime">${esc(b.booking_date.slice(5).replace('-','/'))}　${esc(String(b.start_time).slice(0,5))}〜${esc(minutesToTime(timeToMinutes(b.start_time)+(Number(b.minutes)||30)).slice(0,5))}</div><div>${esc(b.customer_name||'')}　${esc(b.menu_name||'')}　${Number(b.minutes)||30}分</div><div class="monthlyBookingEditHint">タップして予約を編集</div></div>`).join('')}

function addQuarterOptions(select){if(!select)return;const first=[...select.options].find(o=>!o.value)||null,current=select.value;const byValue=new Map([...select.options].filter(o=>o.value&&timeToMinutes(o.value)<22*60).map(o=>[String(o.value).slice(0,5),o]));const all=[];for(let q=DAY_START;q<=LAST_VISIBLE_START;q+=15){const value=minutesToTime(q),key=value.slice(0,5),o=byValue.get(key)||document.createElement('option');o.value=value;o.textContent=key;all.push(o)}select.replaceChildren(...(first?[first]:[]),...all);if(current&&timeToMinutes(current)<22*60)select.value=current}
function addQuarterGuides(){for(const lane of document.querySelectorAll('#scheduleLane,#lane')){if(lane.querySelector('.quarterGuide'))continue;for(let m=DAY_START+15;m<DAY_END;m+=30){const g=document.createElement('div');g.className='quarterGuide';g.style.left=`${(m-DAY_START)*PX_PER_MINUTE}px`;lane.appendChild(g)}}}
async function fetchDayState(date){const[slots,bookings,blocked]=await Promise.all([supabase.from('nakano_open_slots').select('*').eq('slot_date',date),supabase.from('nakano_bookings').select('*').eq('booking_date',date).eq('status','confirmed'),supabase.from('nakano_blocked_times').select('*').eq('blocked_date',date)]);if(slots.error||bookings.error||blocked.error)throw slots.error||bookings.error||blocked.error;blockedRows=blocked.data||[];blockedRowsDate=date;return{slots:slots.data||[],bookings:bookings.data||[],blocked:blockedRows}}
function renderQuarterBackground(slots){const date=selectedDate(),map=new Map(slots.map(r=>[String(r.start_time).slice(0,5),!!r.is_open]));for(const lane of document.querySelectorAll('#scheduleLane,#lane')){if(lane.dataset.quarterOverlayDate===date&&lane.querySelector('.quarterOpenOverlay'))continue;lane.querySelectorAll('.quarterOpenOverlay').forEach(x=>x.remove());for(let m=DAY_START;m<DAY_END;m+=15){const t=minutesToTime(m).slice(0,5),d=document.createElement('div');d.className=`quarterOpenOverlay ${map.get(t)?'open':'closed'}`;d.style.left=`${(m-DAY_START)*PX_PER_MINUTE}px`;d.style.width=`${15*PX_PER_MINUTE}px`;lane.insertBefore(d,lane.firstChild)}lane.dataset.quarterOverlayDate=date}}
function beginLocalOpenCloseWrite(ms=2500){suppressRealtimeUntil=Math.max(suppressRealtimeUntil,Date.now()+ms);suppressQuarterEnhanceUntil=Math.max(suppressQuarterEnhanceUntil,Date.now()+900)}
function invalidateQuarterUI(){const box=$('slots');if(box)delete box.dataset.hourUiReadyDate;for(const lane of document.querySelectorAll('#scheduleLane,#lane')){delete lane.dataset.quarterOverlayDate;lane.querySelectorAll('.quarterOpenOverlay').forEach(x=>x.remove())}}
async function refreshOpenCloseUI(){suppressQuarterEnhanceUntil=Math.max(suppressQuarterEnhanceUntil,Date.now()+900);invalidateQuarterUI();await refreshQuarterUI();if(isAdmin()&&typeof window.loadAdminTimes==='function')await window.loadAdminTimes();if(isAdmin()&&typeof window.loadEditTimes==='function'&&!$('editCard')?.classList.contains('hidden'))await window.loadEditTimes()}
async function toggleQuarterSlot(time,isOpen,button=null){const date=selectedDate();if(!date)return;beginLocalOpenCloseWrite();if(button)button.disabled=true;try{const{error}=await supabase.from('nakano_open_slots').upsert({slot_date:date,start_time:time,is_open:!isOpen},{onConflict:'slot_date,start_time'});if(error)throw error;await refreshOpenCloseUI()}catch(e){console.error(e);alert('変更できませんでした。')}finally{if(button)button.disabled=false}}
async function renderAdminQuarterOpenClose(state){if(!isAdmin())return;const box=$('slots'),date=selectedDate();if(!box||!date)return;if(box.dataset.hourUiReadyDate===date&&box.querySelector('.hourSlotGroup'))return;const{slots,bookings,blocked}=state||await fetchDayState(date),slotMap=new Map(slots.map(r=>[String(r.start_time).slice(0,5),r]));box.classList.add('hourlySlots');box.innerHTML='';for(let hour=8;hour<=21;hour++){const group=document.createElement('div');group.className='hourSlotGroup';group.innerHTML=`<div class="hourSlotTitle">${hour}時</div><div class="hourSlotButtons"></div>`;const buttons=group.querySelector('.hourSlotButtons');for(const minute of[0,15,30,45]){const total=hour*60+minute;if(total>LAST_VISIBLE_START)continue;const label=`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,row=slotMap.get(label),isOpen=!!row?.is_open,slotStart=total,slotEnd=total+15;const booking=bookings.find(b=>overlaps(slotStart,slotEnd,timeToMinutes(b.start_time),timeToMinutes(b.start_time)+(Number(b.minutes)||30))),blockedItem=blocked.find(bt=>overlaps(slotStart,slotEnd,timeToMinutes(bt.start_time),blockEndMinutes(bt.end_time))),busy=booking||blockedItem,b=document.createElement('button');b.type='button';b.className=`hourQuarter ${busy?'busy':isOpen?'open':'closed'}`;b.innerHTML=`<span class="slotTime">${String(minute).padStart(2,'0')}</span><span class="slotLabel">${booking?'予約':blockedItem?'予定':isOpen?'空き':'CLOSE'}</span>`;b.onclick=()=>{if(booking){document.querySelector(`.bookingBlock[data-booking-id="${booking.id}"]`)?.click();return}if(blockedItem){openBlockedEditor(blockedItem);return}toggleQuarterSlot(`${label}:00`,isOpen,b)};buttons.appendChild(b)}box.appendChild(group)}box.dataset.hourUiReadyDate=date;const p=[...box.parentElement.querySelectorAll('p.muted')].find(x=>x.textContent.includes('30分単位')||x.textContent.includes('15分単位'));if(p)p.textContent='15分単位で受付可否を変更できます。予定の枠はタップすると時間を編集できます。'}
async function refreshQuarterUI(){const date=selectedDate();if(!date)return;try{const state=await fetchDayState(date);renderQuarterBackground(state.slots);if(isAdmin())await renderAdminQuarterOpenClose(state);setTimeout(()=>hydrateBlockedBlocks(),40)}catch(e){console.warn('15分表示の更新に失敗',e)}}
async function upsertRows(rows){for(let i=0;i<rows.length;i+=500){const{error}=await supabase.from('nakano_open_slots').upsert(rows.slice(i,i+500),{onConflict:'slot_date,start_time'});if(error)throw error}}
function installQuarterBulkControls(){if(!isAdmin())return;for(const[id,open]of[['openAll',true],['closeAll',false]]){const b=$(id);if(!b||b.dataset.quarterBulk)return;b.dataset.quarterBulk='1';b.onclick=null;b.addEventListener('click',async()=>{const date=selectedDate();if(!date)return;b.disabled=true;try{beginLocalOpenCloseWrite(3500);await upsertRows(quarterTimes().map(start_time=>({slot_date:date,start_time,is_open:open})));await refreshOpenCloseUI()}catch(e){console.error(e);alert('一括変更できませんでした。')}finally{b.disabled=false}})}for(const[id,open]of[['openMonth',true],['closeMonth',false]]){const b=$(id);if(!b||b.dataset.quarterBulk)return;b.dataset.quarterBulk='1';b.onclick=null;b.addEventListener('click',async()=>{const month=$('month')?.value;if(!month)return;const label=open?'OPEN':'CLOSE';if(!confirm(`${month} を全部${label}にしますか？`))return;b.disabled=true;const msg=$('monthMsg');if(msg)msg.textContent='変更しています…';try{const rows=[];for(const date of monthDates(month))for(const start_time of quarterTimes())rows.push({slot_date:date,start_time,is_open:open});beginLocalOpenCloseWrite(5000);await upsertRows(rows);if(msg)msg.textContent=`${month} を15分単位ですべて${label}にしました。`;if(selectedDate().startsWith(month))await refreshOpenCloseUI()}catch(e){console.error(e);if(msg)msg.textContent='一括変更できませんでした。'}finally{b.disabled=false}})}}
function enhanceQuarterTimes(){if(!isAdmin())return;addQuarterOptions($('adminTime'));addQuarterOptions($('editTime'));for(const id of['blockedStart','blockedEnd']){const el=$(id);if(el)el.step='900'}}

function enhance(){clearTimeout(enhanceTimer);enhanceTimer=setTimeout(()=>{renamePages();ensureDestinationSlot();createGuide();ensureBlockedEditor();scanBlocks();hydrateBlockedBlocks();scrollToCurrentTime();improveAdminLayout();enhanceQuarterTimes();addQuarterGuides();installQuarterBulkControls();if(Date.now()>=suppressQuarterEnhanceUntil)refreshQuarterUI()},100)}

addStyles();createEdges();renamePages();ensureDestinationSlot();createGuide();ensureBlockedEditor();scanBlocks();setupDateWatch();setupRealtime();
setTimeout(()=>{scrollToCurrentTime(true);improveAdminLayout();enhanceQuarterTimes();addQuarterGuides();installQuarterBulkControls();refreshQuarterUI();loadMonthlyBookings();hydrateBlockedBlocks(true)},520);
window.refreshMonthlyBookings=loadMonthlyBookings;
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
window.addEventListener('pointermove',pointerMove,{passive:false});window.addEventListener('pointerup',pointerUp);window.addEventListener('pointercancel',pointerCancel);

import(`./blocked-drag.js?_v=${Date.now()}`);
